### ISSUE TITLE
toCSV() not converting a verse starting with x - \xo ... \xt ... \x* verse text comes here

### ISSUE THREAD

**Issue by csdal** [Bridgeconn/usfm-grammar#106]
I'm converting usfm files into csv.

A sample usfm text
```
\v 26 \x - \xo 3.26 \xt ယစံး\x* ဒ်သိးအကဒုးနဲၣ်အတၢ်တီတၢ် လိၤအကတီၢ်ဖဲအံၤ, ဒ်သိးအကတီဝဲလိၤဝဲဒီးပာ်တီပာ် လိၤပှၤလၢအနာ်ယ့ၣ်ရှူးန့ၣ်လီၤ.
```
`toCSV()` did not convert the text. Instead, it left blank like this: (look at ROM 3: 26)
```
ROM | 3 | 25 | ယွၤပာ်ဖျါထီၣ်အီၤလၢတၢ်လုၢ်,လၢတၢ်နာ် အသွံၣ်အဃိ, ဒ်သိးအကဒုးနဲၣ် အတၢ်တီတၢ်လိၤလၢ တၢ်လဲၤကပာ်တၢ်ဒဲးဘးလၢ ပှၤမၤတ့ၢ်ဝဲဖဲယွၤဝံသးစူၤ တၢ်အတီၢ်ပူၤ,
-- | -- | -- | --
ROM | 3 | 26 |  
-- | -- | -- | --
```

every usfm verse texts starting with `\x - \xo ... \xt ...\x*` are not converted.

**Comment by kavitharaju** [comment]
I see this issue occuring when the level is set to `relaxed`, and not in normal mode parsing.
Isn't that right @csdal ?

**Comment by csdal** [comment]
yes, @kavitharaju

**Comment by kavitharaju** [comment]
As mentioned in the [disclaimer](https://github.com/Bridgeconn/usfm-grammar/blob/master/docs/Disclaimer.md), with several rules relaxed, marker closings are not verified properly in the relaxed mode. This leads to this loss of verses texts.

As [already stated](https://github.com/Bridgeconn/usfm-grammar#usfm-to-json), it is discouraged that you use the `relaxed` mode to avoid loss of information. The right (or the hard) thing to do is fix the markup according to the specification and use the usfm-grammar in the default mode.

But we are also planning to add some validations for footnotes and cross references which are closed all together with one closing marker like this, which would hopefully fix this particular issue.

**Comment by kavitharaju** [comment]
we have a [new release](https://github.com/Bridgeconn/usfm-grammar/releases/tag/v2.0.0-beta.9) that would fix this issue

[npm package](https://www.npmjs.com/package/usfm-grammar)
