### ISSUE TITLE
Provide proper error messages when input is invalid

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#11]
The error messages in beta version is not infirmative enough. Obtain the error messages genarated by OHM library and pass it as the error message for usfm-grammar

**Comment by RobH123** [comment]
Yes, if you look [here](https://github.com/unfoldingWord/content-validation/blob/master/src/core/BCS-usfm-grammar-check.js#L23) you can see how I can helpfully get the warnings out of the parser, but haven't figured out how to extract the (more important) errors. Thanks.

**Comment by joelthe1** [comment]
From [v2.0.0-beta.3](https://github.com/Bridgeconn/usfm-grammar/releases/tag/v2.0.0-beta.3), the response on encountering an error is something like:
```
{
  "_messages": {
    "_error": "Line 1797, col 49:\n  1796 | \\w γὰρ|lemma=\"γάρ\" strong=\"G10630\" x-morph=\"Gr,CC,,,,,,,,\"\\w*\n> 1797 | \\k-s | x-tw=\"rc://*/tw/dict/bible/other/know\" \\w*\n                                                         ^\n  1798 | \\w ἴστε|lemma=\"εἴδω\" strong=\"G14920\" x-morph=\"Gr,V,MEA2,,P,\" \\w*,\nExpected \"\\\\\", \"-e\", \"-s\", or \" \""
  }
}
```

So you should be able to read just like you would the warnings.

**Comment by RobH123** [comment]
Right @joelthe1 but for my need, I'm currently only using the validate() function which doesn't return them. Looks like maybe I should switch to using the toJSON() function (even though I don't use the JSON)?

**Comment by RobH123** [comment]
Ok @joelthe1, I got it working how I needed in the first function [here](https://github.com/unfoldingWord/content-validation/blob/master/src/core/BCS-usfm-grammar-check.js). Thanks to all. :)
