### ISSUE TITLE
"stub" books

### ISSUE THREAD

**Issue by DCNemesis** [Bridgeconn/usfm-grammar#114]
Similar to the stub chapters, I noticed that translators may create an SFM file with an `/id` marker, book title, and little else. These fail to be processed. Perhaps this is the intended behavior, but when I'm calling usfm-grammar from within python the error messages don't get through. So, I have to hunt down all the books that are empty json files and find which are actual errors and which are just stubs. My preference would probably be to have a json produced with the book name and a warning to set it apart from the ones where some other error caused the failure.

**Comment by joelthe1** [comment]
@kavitharaju I think this might be worth relaxing in the relaxed mode with a warning.
