### ISSUE TITLE
JSON Schema for 3.x

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#180]
Once the JSON output schema is validated and finalized after enough manual tests in the python module, need to define a schema, which can be used for automated testing for further developments in js or other modules.

Also documentations about how it is different from 2.x would be good to have.

**Comment by kavitharaju** [comment]
Might come useful https://github.com/coveooss/json-schema-for-humans

**Comment by kavitharaju** [comment]
[here](https://github.com/kavitharaju/usfm-grammar/blob/dev/docs/OutputComparisons.md#difference-in-json-outputs-of-2x-and-3x) is some output samples of current v3 JSON. Sharing for discussion and finalizing output structure.

**Comment by kavitharaju** [comment]
We could support two JSON schemas. 
- The regular one contains necessary complex nesting and arrays which would be a consistent format that provides the structural pasred format
- A flat one, that provides minimum nestings and at the cost of semantic strcutures of elements.
Both the output formats should be giving consistent outputs irrespective of the complexity and nesting of input USFM

**Comment by kavitharaju** [comment]
[JSON_refactor.md](https://github.com/Bridgeconn/usfm-grammar/files/10313281/JSON_refactor.md)

@joelthe1 How does these JSON outputs look?
Sharing for review.

**Comment by joelthe1** [comment]
This is done within the scope described. High-level schema defined for the newly proposed USJ format.
