### ISSUE TITLE
Should fig maker without attribute name be supported?

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#181]
The USFM 3 documentation on [fig](https://ubsicap.github.io/usfm/characters/index.html#fig-fig) says

```
Compatibility with USFM 1.x and 2.x: If a USFM parser encounters a list of un-named attributes using a vertical bar separator within \fig ...\fig* these should be interpreted according to the strict USFM 2.x order.
```
Does that mean our parser should provide these backward compatibility?

**Comment by joelthe1** [comment]
Decided to not support backward compatibility with 2.x and to document this use-case.
