### ISSUE TITLE
Generate USFM from other formats

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#217]
To be able to provide round trippability with our various formats like USJ, USX and syntax tree we need to be able to generate USFM from these formats

- [x] USX to USFM
- [x] USJ to USFM
- [ ] Table/List/CSV to USFM
- [ ] Syntax tree to USFM (Not sure if this is useful/feasible)

**Comment by kavitharaju** [comment]
That is in our plan. Hopefully in a couple of months we would be able to get the early versions out.
Here is an issue for you to keep watch on https://github.com/Bridgeconn/usfm-grammar/issues/152 .

**Comment by joelthe1** [comment]
Closing this issue in favor of https://github.com/Bridgeconn/usfm-grammar/issues/287 (decided to not implement `Syntax tree to USFM`).
