### ISSUE TITLE
Import error in usfm parser

### ISSUE THREAD

**Issue by shimilgithub** [Bridgeconn/usfm-grammar#238]
Unable to import `usfm parser`. Showing this error with `usfm b5`

![MicrosoftTeams-image (17)](https://github.com/Bridgeconn/usfm-grammar/assets/54615511/f4960dc6-60d4-44c8-87dd-d2e381b7ab2b)

**Comment by AnonymousWalker** [comment]
upvoted!

**Comment by kavitharaju** [comment]
Thanks @shimilgithub and @AnonymousWalker for reporting the issue.

The issue was due to tree-sitter version 0.22.0 and above not being supported.
Our newest release `usfm-grammar==3.0.0-beta.7` should help you out.
