### ISSUE TITLE
Trying to build py-usfm-parser to use latest changes

### ISSUE THREAD

**Issue by trevorpfiz** [Bridgeconn/usfm-grammar#285]
Sorry in advance! I am trying to clone the repo and follow https://github.com/Bridgeconn/usfm-grammar/blob/master/docs/Dev_notes.md to locally build an updated version of the `py-usfm-parser` to use the changes in #283, but I am running into issues. I am probably just doing something wrong, but can you confirm that the `Dev_notes.md` is up-to-date and works E2E?

Thanks!

**Comment by kavitharaju** [comment]
Yes, the `Dev_notes.md`  is what you should be following. It has more details but I can list out the main steps you would need in your specific case:

1. Install the `py-usfm-parser` module in your project environment (`pip install usfm-grammar/py-usfm-parser`).

NOTE: the `usfm-grammar` library has a separate grammar library as its dependency. If you want to update that too, do the following:
2. Build the grammar in the `tree-sitter-usfm3` module (`tree-sitter generate`).
3. Install the latest grammar (`pip install usfm-grammar/tree-sitter-usfm3`). 
 
Running provided tests after each step would help identify where the issue might be.

Hope this helps.

**Comment by joelthe1** [comment]
@trevorpfiz v3.0.0 is out with the latest changes! Please let us know any feedback.

**Comment by trevorpfiz** [comment]
> @trevorpfiz v3.0.0 is out with the latest changes! Please let us know any feedback.

I saw! Thank you! These were the only errors I was still getting from the BSB USFM:
```
Errors in file data/bsb_usfm/38ZECBSB.usfm: [('At Point(row=553, column=0)', '\\d\n\\v 1 This is the burden of the word of the LORD concerning Israel.'), ('At Point(row=554, column=65)', '.')]
Errors in file data/bsb_usfm/35HABBSB.usfm: [('At Point(row=306, column=0)', '\\it For the choirmaster. With stringed instruments.\n\\it*'), ('At Point(row=306, column=23)', '.'), ('At Point(row=306, column=50)', '.')]
```

But I think these are just caused by invalid data? So I changed:

```
\pc 
\b
\it For the choirmaster. With stringed instruments.
\it* 
```
to
```
\b
\pc 
\it For the choirmaster. With stringed instruments.
\it* 
```
and
```
\s1 The Coming Deliverance of Jerusalem
\b
\d
\v 1 This is the burden of the word of the LORD concerning Israel. 
```
to
```
\s1 The Coming Deliverance of Jerusalem
\b
\pc
\v 1 This is the burden of the word of the LORD concerning Israel. 
```

Now the parser gets through the whole BSB and is working great! Thanks again!
