### ISSUE TITLE
Support for CSV/TSV Export

### ISSUE THREAD

**Issue by beniza** [Bridgeconn/usfm-grammar#29]
There are several useful use cases of having a USFM file in a CSV or Tab Separated format. (Tab is preferred as the natural text may contain several commas in it). Could you please provide an export option?

Also, please include the errors or warnings encountered during the validation/conversion process.

**Comment by joelthe1** [comment]
Are you referring to only having the scripture text in the Tab format without any of the other markers?

**Comment by beniza** [comment]
yes! that's what I meant.

**Comment by joelthe1** [comment]
That sounds like a good idea to me. Will keep this issue around for tracking but might be after finishing with some of the other tasks already in-progress.

**Comment by joelthe1** [comment]
I know we had talked about revamping the API as we are expanding capabilities. I think we should have fully qualified API names like `parseUsfmToCsv`, `parseJsonToUsfm`, etc.

**Comment by beniza** [comment]
yep, I agree with Joel that having fully qualified API names would help.

**Comment by kavitharaju** [comment]
The API is changed. Now we CSV/TSV can be obtained as follows
```
const grammar = require('usfm-grammar');
. . .
let jsonOutput = grammar.USFMparser.parseUSFM(input);
let csvString = grammar.JSONparser.toCSV(jsonOutput);
let tsvString = grammar.JSONparser.toTSV(jsonOutput);
```

**Comment by beniza** [comment]
Thank you @Kavitha Raju <kavitharaju18@gmail.com>.
