### ISSUE TITLE
Handling Split Verses

### ISSUE THREAD

**Issue by beniza** [Bridgeconn/usfm-grammar#30]
In some Bibles verses are split into two (or more) sub parts. Please see an example from GNT below:
![image](https://user-images.githubusercontent.com/4908971/60146177-2d4ffd80-97e6-11e9-89cd-46225abbfe0f.png)

The code handling `verse number` doesn't seem to handle this case. 
https://github.com/Bridgeconn/usfm-grammar/blob/9d9a1c1ea2d04058623c85c991209c397251bbe9/usfm.ohm#L62

**Comment by beniza** [comment]
fixed?

**Comment by joelthe1** [comment]
Yes, the latest release incorporates fixes for these cases and parses them correctly.

**Comment by beniza** [comment]
Great! thanks for working on this :)
