### ISSUE TITLE
Online testing page

### ISSUE THREAD

**Issue by beniza** [Bridgeconn/usfm-grammar#31]
Would it be possible to setup an online page where we can test the USFM grammar against various files?

**Comment by joelthe1** [comment]
We are putting this on the roadmap. I can see the value of this.

**Comment by beniza** [comment]
Thank you Joel

**Comment by joelthe1** [comment]
This is now completed. Please lookup the README.md for more details.

**Comment by beniza** [comment]
Thank you... it's working!
