### ISSUE TITLE
"Undefined" coming in verse['text'] of verses with `\li#` marker

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#37]
The text property of the verse object is where the whole text of the verse is coming without any markers or metadata.
For a verse with list in it, it is not coming as expected.
It has happened after the list json structure changed for reverse convertability.

**Comment by sakhmedbayev** [comment]
Same here, cannot parse this usfm

```
\id HAB 45HABGNT92.usfm, Good News Translation, June 2003
\c 3
\s1 A Prayer of Habakkuk
\p
\li1
\v 2 Сыновья\f + \fr 10:2 \ft Слово «сыновья» также может означать «потомки» или «народы». Многие из этих имён известны как исторические названия народов. Также в ст. \+xt 10:3, 4, 6, 7, 20-23, 29 и 31\+xt*.\f* Иафета:
```

**Comment by kavitharaju** [comment]
The `\li#` marker is not used correctly here. The USFM [spec says](https://ubsicap.github.io/usfm/lists/index.html#li) it should have text in it. 

May be it is [`\lim#` ](https://ubsicap.github.io/usfm/lists/index.html#lim)that you need here.
