### ISSUE TITLE
Throwing error at \q within \d

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#43]
```
\id GEN
\c 56
\s ପରମେଶ୍ୱରଙ୍କ ଉପରେ ନିର୍ଭରଶୀଳତାର ପ୍ରାର୍ଥନା
\d ପ୍ରଧାନ ବାଦ୍ୟକର ନିମନ୍ତେ ଯୋନତ୍‍-ଏଲମ୍‍
\q ରହୋକୀମ୍‍ ସ୍ୱରରେ ଦାଉଦଙ୍କର ଗୀତ। ମିକ୍ତାମ୍‍; ପଲେଷ୍ଟୀୟମାନେ ତାଙ୍କୁ ଗାଥ୍‍ ନଗରରେ ଧରିବା ସମୟରେ ରଚିତ।
\q
\v 1 ହେ ପରମେଶ୍ୱର, ମୋତେ ଦୟା କର; କାରଣ ମୋହର ଶତ୍ରୁ ମୋତେ ଗ୍ରାସ କରିବାକୁ ଉଦ୍ୟତ;
\q ସେ ସାରାଦିନ ଯୁଦ୍ଧ କରି ମୋ’ ପ୍ରତି ଉପଦ୍ରବ କରଇ।
\q
```

giving error

{
ERROR: "Line 5, col 4:
  4 | \d ପ୍ରଧାନ ବାଦ୍ୟକର ନିମନ୍ତେ ଯୋନତ୍‍-ଏଲମ୍‍
&gt; 5 | \q ରହୋକୀମ୍‍ ସ୍ୱରରେ ଦାଉଦଙ୍କର ଗୀତ। ମିକ୍ତାମ୍‍; ପଲେଷ୍ଟୀୟମାନେ ତାଙ୍କୁ ଗାଥ୍‍ ନଗରରେ ଧରିବା ସମୟରେ ରଚିତ।
         ^
  6 | \q
Expected "\\""
}

**Comment by kavitharaju** [comment]
Here we see a \q marker after \d, on line 4 and 5. There is some text following it as well, which seems to be part of the title description(\d content) as the verses are starting only below that. So the \q is coming within the contents of the \d marker, I suppose.
usfm-grammar does not accept this as  it accepts only plain text/notes/milestones  within the \d marker. I cannot find any support for this usage from the online usfm/usx documentations.

**Comment by joelthe1** [comment]
Discussions so far haven't yielded any decisive evidence on which route to take. Triaging this for now.

**Comment by joelthe1** [comment]
@kavitharaju Is there an update on this?

**Comment by kavitharaju** [comment]
We haven't accomodated a paragraph seperation(\q) within a descriptive title(\d) in the normal mode grammar. But the relaxed mode parsing would overlook this and parses the above snippet successfully

**Comment by klassenjm** [comment]
Hi @joelthe1 , @kavitharaju 

```
\s section head
\d descriptive / hebrew sub-title
\q poetic text
\q
\v 1 poetic text
```

This is a sequence I have not seen before (assume this is `PSA`). The descriptive title in Psalm 56 is rather long. It has multiple 'parts' (perhaps 5, depending on how you break it up).

I imagine that the translator of this text is simply trying to break it into parts. The various other examples I have looked at (in English) have periods, commas, or semi-colons between parts.

I understand what Kavitha says - that `\q` appears to be implied to be 'within' `\d`. But `\q` is a new paragraph. In poetic text we have the concept of stanzas, often a bunch of `\q1`, `\q2` etc. between 2 `\b` markers. But there is not a way to imply that `\q` is within `\d`.

For this, the only 2 things I can suggest myself are:
1. Remove the \q, and add punctuation (if that would work in this language)
2. Use the USFM discretionary break syntax `//`. So:

```
\d ପ୍ରଧାନ ବାଦ୍ୟକର ନିମନ୍ତେ ଯୋନତ୍‍-ଏଲମ୍‍ // ରହୋକୀମ୍‍ ସ୍ୱରରେ ଦାଉଦଙ୍କର ଗୀତ। ମିକ୍ତାମ୍‍; ପଲେଷ୍ଟୀୟମାନେ ତାଙ୍କୁ ଗାଥ୍‍ ନଗରରେ ଧରିବା ସମୟରେ ରଚିତ।
```

I realize you're probably not asking how to adjust the text - but whether or how to validate this text. If it was up to me - I would identify this as invalid. Within scripture text, `\q#` normally only occurs together with or after verse 1.

My thoughts.

**Comment by joelthe1** [comment]
That is an insightful answer. Thank you very much @klassenjm! 
But this is a good segue to #61 (use // to force a new line). Any thoughts on that would be valuable too!

**Comment by joelthe1** [comment]
Based on the discussion we continue to treat this this usage as an error in `usfm-grammar`.
