### ISSUE TITLE
Update Ohm Version

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/usfm-grammar#48]
There is a [newer version of ohm.js](https://github.com/harc/ohm/releases/tag/v0.15.0) available that we should ideally upgrade to.

**Comment by kavitharaju** [comment]
Even though this version is released on github, NPM still has the previous(0.14) as the latest, which we are using. Should we download the github release and use it instead of the NPM package?

**Comment by joelthe1** [comment]
I think we can do that for now. I have created an issue with Ohm: https://github.com/harc/ohm/issues/255

**Comment by kavitharaju** [comment]
using ohm-0.15.0 from https://www.npmjs.com/package/ohm-fork
