### ISSUE TITLE
Grammar fails to parse very large files

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#54]
when tested using a large alignment USFM file of size 2.6 MB, the library fails with the following error

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
`

**Comment by joelthe1** [comment]
Something like this might help `export NODE_OPTIONS=--max_old_space_size=4096`

**Comment by kavitharaju** [comment]
It worked. I set 8 GB
