### ISSUE TITLE
Error while Parsing

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/usfm-grammar#57]
Unable to parse file: https://git.door43.org/Door43-Catalog/hi_irv/src/branch/master/43-LUK.usfm
Not sure if this is a valid error or not but worth investigating since this is a 'published' version of the file.

**Comment by kavitharaju** [comment]
There are several issues in that file which lead to it not parsing. All of them are of similar nature though

1. more than 30 empty `\it \it*` markers
2. more than 150 empty `\bdit \bdit*` markers
3. more than 600 empty `\wj \wj*` markers
4. around 40 `\it \+wj .... ` markers that span across multiple lines and multiple milestones(do not know, this this valid or not)
 5. around 200 consecutive milestone end markers without a start in between `\zaln-e\*\zaln-e\*`

**Comment by joelthe1** [comment]
Would the relaxed parser work with this?

**Comment by kavitharaju** [comment]
yes. The file has been tested with RELAXED parsing and it is parsing successfully
