### ISSUE TITLE
Re-design the JSON output

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/usfm-grammar#60]
Currently there are 3 main JSON outputs.
1. Output of normal usfm parsing
2. Output of USFM parsing in SCRIPTURE only mode
3. Output of relaxed mode USFM parsing

The reverse parse is built based on 1.

The new JSON structure should be common to all these. Also must usable to re-create the USFM (reverse parse).

**Comment by kavitharaju** [comment]
x-special/nautilus-clipboard
copy
file:///home/kavitha/Documents/PEG%20JS%20and%20USFM/try_out_usfm-grammar/sample.usfm

The above small sample USFM was considered and the suggested JSON was designed with it
x-special/nautilus-clipboard
copy
file:///home/kavitha/Documents/PEG%20JS%20and%20USFM/try_out_usfm-grammar/sample_suggested.json



**Major of the Suggested Changes**
- not separating markers in chapters and verses as metadata. But including everything in contents
- text values given as plain strings in contents array and not as objects with 'text' as key
- except for id, c, v, f and x which have differnt keys and heirachichal JSOn structure, everything else has maker name as key and contents, if any, as values

**Points that need further consideration**
- Would the header markers take inner elements? if not avoid the array and give plain text
- When \p and similar para markers come within the verse, should the verse text ge given as value of the para marker or as separate text item in contents array?
- do we need "inLine" in the JSON. Should we just follow the newLine criteria as recommended by spec, for each marker?

**Comment by joelthe1** [comment]
This looks good for now. Let's go ahead with implementing this.
