### ISSUE TITLE
Verse text is parsed incorrectly while in relaxed mode

### ISSUE THREAD

**Issue by sakhmedbayev** [Bridgeconn/usfm-grammar#71]
While parsing the following USFM using this setup `new grammar.USFMParser(
      data,
      grammar.LEVEL.RELAXED
    );`:

```
\c 1
\s1 Сотворение мира
\p
\v 1 В начале Всевышний\f + \fr 1:1 \fk Всевышний \ft – на языке оригинала: «Элохим» – слово, родственное арабскому «Аллах». См. приложение V.\f* сотворил небо и землю.
```

getting this JSON output:

```
"chapters": [
    {
      "chapterNumber": "1",
      "contents": [
        {
          "s1": "Сотворение мира"
        },
        {
          "p": null
        },
        {
          "verseNumber": "1",
          "contents": [
            "В начале Всевышний",
            {
              "f": "+"
            },
            {
              "fr": "1:1"
            },
            {
              "fk": [
                "Всевышний",
                {
                  "ft": "– на языке оригинала: «Элохим» – слово, родственное арабскому «Аллах». См. приложение V.",
                  "closing": "\\f*"
                },
                "сотворил небо и землю."
              ]
            }
          ],
          "verseText": "В начале Всевышний"
        },
```

notice, how a part of the verse text - `"сотворил небо и землю." ` - became a part of `"fk":` array

**Comment by kavitharaju** [comment]
As the [disclaimer](https://github.com/Bridgeconn/usfm-grammar/blob/master/docs/Disclaimer.md) says

_Marker closing in LEVEL.RELAXED parsing_

_With several rules relaxed in this grammar, we are not validating if a marker is closed properly with its own closing marker. So which ever closing is encountered after it, would be treated as a valid closing for any marker. This would be evident in the formation of JSON object for footnotes and cross-refs_

This policy of not checking for correct closing marker is leading to this issue as well, in relaxed mode. What we recommend is to always use the normal mode to ensure the correct validation of USFM and the proper parsed output JSON.
