### ISSUE TITLE
Error while parsing file

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/usfm-grammar#72]
Unable to parse https://git.door43.org/unfoldingWord/el-x-koine_ugnt/raw/branch/master/50-EPH.usfm
```
{
  "ERROR": "Line 1797, col 49:\n  1796 | \\w γὰρ|lemma=\"γάρ\" strong=\"G10630\" x-morph=\"Gr,CC,,,,,,,,\"\\w*\n> 1797 | \\k-s | x-tw=\"rc://*/tw/dict/bible/other/know\" \\w*\n   
^\n  1798 | \\w ἴστε|lemma=\"εἴδω\" strong=\"G14920\" x-morph=\"Gr,V,MEA2,,P,\" \\w*,\nExpected \"\\\\\", \"-e\", \"-s\", or \" \""
}
```

Also, we should change the key to `_error`. And is it possible to have this in the same structure as the `_warnings` like
```
"_messages": {
    "_warnings": [
      "Empty lines present. "
    ]
  }
```

**Comment by kavitharaju** [comment]
In the error message, I see that on line, 1797, a milestone marker is started as `\k-s`. But at the end of the line it is closed with a `\w*`. It is this improper closing of milestone marker that has caused the error. Changing the `\w*` to `\*` enables the file to be parsed.

About changing the JSON key and structure, yes. Shall do that

**Comment by joelthe1** [comment]
This has been modified.
