### ISSUE TITLE
Bad demo link in ReadMe

### ISSUE THREAD

**Issue by RobH123** [Bridgeconn/usfm-grammar#75]
http://usfm.vachanengine.org/ just gives a 502 error

**Comment by RobH123** [comment]
On https://npm.runkit.com/usfm-grammar I found a link to http://usfm.bridgeconn.com/ but that gives an nginx config error.

**Comment by joelthe1** [comment]
Thanks for the report @RobH123. This has been fixed http://usfm.vachanengine.org/ (still testing things though)
