### ISSUE TITLE
Error message seems to have wrong line number

### ISSUE THREAD

**Issue by RobH123** [Bridgeconn/usfm-grammar#81]
Hi there,
I'm trying to check [this](https://git.door43.org/unfoldingWord/hbo_uhb/src/branch/master/08-RUT.usfm) and getting an error on line 62:
```
Line 62, col 19:
61 | \w וַ⁠יִּשְׂא֣וּ|lemma="נָשָׂא" strong="c:H5375" x-morph="He,C:Vqw3mp"\w* 
62 | \w לָ⁠הֶ֗ם|lemma="" strong="l" x-morph="He,R:Sp3mp"\w* 
                         ^ 
63 | \w נָשִׁים֙|lemma="אִשָּׁה" strong="H0802" x-morph="He,Ncfpa"\w* 
Expected not "\""
```
But that doesn't seem to match the lines in the file (and so I can't actually be sure what it's failing on)??? (You can also see it [here](https://unfoldingword.github.io/content-validation/#/Core%20Mid-level%20Filetype%20Checking%20Functions?id=section-usfm-grammar-check-from-bcs) and [here](https://unfoldingword.github.io/content-validation/#/Book%20Package%20Checker%20Demo?id=bookpackagecheck).)

**Comment by kavitharaju** [comment]
The reason for the error is that there is an empty attribute. Lemma attribute is mentioned, but there is not value in it. 
```
\w לָ⁠הֶ֗ם|lemma="" strong="l" x-morph="He,R:Sp3mp"\w*
```
The line number in error message says 62, but actually the line is 67. The reason for this difference is that, there are empty lines present in the file, which the parser eliminated while normalizing.

**Comment by RobH123** [comment]
Thanks for the fast response and pointing out the issues. I guess I can write code in my app to count the blank lines above the error line and then add that number to the given line number. But of course, the best place to do that would be inside this package.
