### ISSUE TITLE
Expand schema for \w inside footnote

### ISSUE THREAD

**Issue by RobH123** [Bridgeconn/usfm-grammar#86]
Hi there,

Would it be possible to allow this line:

\f + \ft K \w כסלו|lemma="כִּסְלֵו" strong="H3691" x-morph="He,Np"\w*\f*

as seen at https://git.door43.org/unfoldingWord/hbo_uhb/src/branch/master/16-NEH.usfm#L19

Thanks.

**Comment by kavitharaju** [comment]
The USFM sepc doesn't say anything about `\w` being allowed within footnotes, where as it gives [a list of content markers](https://ubsicap.github.io/usfm/notes_basic/fnotes.html#footnote-content-elements), which doesn't include `\w`.

We need to look more into this and find out if it is a valid usage.

**Comment by RobH123** [comment]
Good point. We need to ask the USFM spec maintainer for clarity on this. Do you want to do that, or should I?

**Comment by kavitharaju** [comment]
This appears to be  a case of [character marker nesting](https://ubsicap.github.io/usfm/characters/nesting.html). 
The `\f` markers which are character level markers when needs to have other character level markers, it should be indicated with `+`, example `\+w`.

This example, is taken from [usfm documentation](https://ubsicap.github.io/usfm/characters/nesting.html).

```
\p When the \nd Lord\nd* \f + \fr 2.4: \fk the \+nd Lord\+nd*: \ft Where the Hebrew text
has Yahweh, traditionally transliterated as Jehovah,
```

It shows `\nd` marker. I think similar rule would appy to `\w` marker as well.
So the correct usage in your case would be 

```
\f + \ft K \+w כסלו|lemma="כִּסְלֵו" strong="H3691" x-morph="He,Np"\+w*\f*
```

This is already supported in usfm-grammar.
