### ISSUE TITLE
Expand schema for empty lemma fields

### ISSUE THREAD

**Issue by RobH123** [Bridgeconn/usfm-grammar#87]
Hi again,

Would it be possible to expand the schema to allow this line:

\w לִ⁠י֒|lemma="" strong="l" x-morph="He,R:Sp1cs"\w*

as seen at https://git.door43.org/unfoldingWord/hbo_uhb/src/branch/master/16-NEH.usfm#L44

This is a genuine situation where there's no actual "root word" in the Hebrew.

Thanks.

**Comment by joelthe1** [comment]
We could make this a warning in the system.

**Comment by kavitharaju** [comment]
Updated grammar. Now the following cases are accepted
```
\id GEN
\mt1 ഉല്പത്തിപുസ്തകം
\c 1
\p
\v 1 ആദിയിൽ ദൈവം \w ആകാശവും |lemma="ആകാശം" strong="l" x-morph="He,R:Sp1cs"\w* ഭൂമിയും സൃഷ്ടിച്ചു.
\v 2 ആദിയിൽ ദൈവം \w ആകാശവും |lemma="" strong="l" x-morph="He,R:Sp1cs"\w* ഭൂമിയും സൃഷ്ടിച്ചു.
\v 3 ആദിയിൽ ദൈവം \w ആകാശവും|"ആകാശം"\w* ഭൂമിയും സൃഷ്ടിച്ചു.
\v 4 ആദിയിൽ ദൈവം \w ആകാശവും|ആകാശം\w* ഭൂമിയും സൃഷ്ടിച്ചു.
```

And the following are not
```
\v 6 ആദിയിൽ ദൈവം \w ആകാശവും| \w* ഭൂമിയും സൃഷ്ടിച്ചു.

\v 1 ആദിയിൽ ദൈവം \w ആകാശവും |lemma=ആകാശം strong="l" x-morph="He,R:Sp1cs"\w* ഭൂമിയും സൃഷ്ടിച്ചു.

\v 1 ആദിയിൽ ദൈവം \w ആകാശവും |lemma= strong="l" x-morph="He,R:Sp1cs"\w* ഭൂമിയും സൃഷ്ടിച്ചു.

\v 1 ആദിയിൽ ദൈവം \w ആകാശവും |lemma strong="l" x-morph="He,R:Sp1cs"\w* ഭൂമിയും സൃഷ്ടിച്ചു.

```

**Comment by joelthe1** [comment]
Thanks @kavitharaju. Does this also include adding warnings for the cases where the lemma is an empty string?

**Comment by kavitharaju** [comment]
Yes. It would give Warning when ever an attribute has empty string as value
