### ISSUE TITLE
Decide on descriptive names vs using tag names in the converted JSON

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/usfm-grammar#89]
This is to further discuss the point [that came up](https://github.com/Bridgeconn/usfm-grammar/issues/84#issuecomment-719680291) about having descriptive names in the key of the USFM converted JSON for specific tags like `\li` -> `list`.

**Comment by kavitharaju** [comment]
To continue this discussion, adding the details of named sub-structures in output JSON.

All kinds of footnotes \f, \fe and \ef are mentioned as 'footnote' in JSON. But the closing marker gives idea on which is which. Same is applicable for cross-references (\x, \xt, \xe) also. The key-word "caller" is used inside these strcutures if present. This is true for the toJSON() output from normal mode parsing. If the --LEVEL.RELAXED flag is set, the key 'footnote' or 'cross-ref' will not be present in output, instead they will be given with corresponding marker itself as key. 

Other than footnotes and cross-refs, lists and tables are also given corresponding descriptive names and combined as strcutured objects with an array or matrix structure, after normal mode USFM to JSON conversion. The key-word 'header' is used inside table structure, if header row is present.

Milestones also are named as "milestone", after normal mode parsing, when they occur in JSON output.

The list of other descriptive property names introduced into the output JSON for both relaxed and normal mode parsing are, book, bookCode, description, meta, chapters, contents, verseNumber, verseText, attributes, defaultAttributes, closing.

**Comment by joelthe1** [comment]
This has been documented in the README.
