### ISSUE TITLE
TSV/CSV Conversion Should Default to `relaxed` mode

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/usfm-grammar#97]
When converting to TSV and CSV mode from the command line the same USFM file errors out when trying to convert to TSV or CSV except when using the option `-l relaxed`. I think we should default to `relaxed` mode whenever the user just wants to convert to TSV or CSV. Specifically I was trying to parse 01-GEN.usfm from [here](https://git.door43.org/Door43-Catalog/hi_irv) file.

Also, I think we should find out why some of those files won't parse. On the command line I just see this:
```
Error parsing the input USFM. 
Cannot read property 'bookCode' of undefined
```
Maybe report filename at least?

**Comment by kavitharaju** [comment]
As per the updated JSON validation we get an error like this 
```
{
  _messages: {
    _error: [
      'instance requires property "book"',
      'instance requires property "chapters"'
    ]
  }
}
```

But here it should report the error in USFM. Shall work on that.

But I dont know if defaulting to relaxed mode for all TSV/CSV conversion is a good idea. As the relaxed mode may accept incorrect usages and give incorrect data, I feel the user should choose that explicitly, other wise we should use, the stricter, normal mode, ensuring correctness of data we extract.

**Comment by kavitharaju** [comment]
The above error was shown because the USFM had errors.
We first convert the input USFM to JSON and that JSON is passed on to be converted to CSV and TSV. 
In this case the resultant JSON of USFM parsing had the error report and it was passed on to the TSV converter method. 


Changed this flow now. It checks if the USFM to JSON converson was successfull before passing it on to the toCSV() or toTSV().

Now the output, error report will be as follows

```
{
  _messages: {
    _error: 'Line 3977, col 6:\n' +
      '  3976 | \\v 18 \\zaln-s | x-strong="H0853" x-lemma="אֵת" x-morph="He,To" x-occurrence="1" x-occurrences="1" x-content="אֶת"\\*\\w परन्तु|x-occurrence="1" x-occurrences="1"\\w*\\zaln-e\\*\n' +
      '> 3977 | \\tl \\zaln-s | x-strong="H0854" x-lemma="אֵת" x-morph="He,R:Sp2fs" x-occurrence="1" x-occurrences="1" x-content="אִתָּ֑⁠ךְ"\\*\\w तेरे|x-occurrence="1" x-occurrences="1"\\w*\n' +
      '              ^\n' +
      '  3978 | \\w संग|x-occurrence="1" x-occurrences="1"\\w*\n' +
      'Expected "xt", "ex", "x", "ef", "fe", "f", "+", "+liv", "+jmp", "+w", "+rb", "+cat", "+ior", "+rq", "+lik", "+litl", "+qac", "+qs", "+wa", "+wh", "+wg", "+ndx", "+sup", "+sc", "+no", "+bdit", "+it", "+bd", "+em", "+wj", "+tl", "+sls", "+sig", "+qt", "+addpn", "+png", "+pn", "+ord", "+nd", "+k", "+dc", "+bk", or "+add"'
  }
}
```

**Comment by joelthe1** [comment]
We will leave the decision to the user whether to use `relaxed` mode or not. The improved error reporting is good.
