### ISSUE TITLE
Deprecate `-o` Option in Command Line

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/usfm-grammar#98]
I think `-o` option is redundant and for all the use-cases I can think a user could simply pipe the output from the tool or use redirections (e.g. `>`) to achieve the same. So it would suffice to have the output simply printed to console.

**Comment by kavitharaju** [comment]
okay. We are to remove the command line options `-o` and `--output`, right?
Shall do that.

**Comment by joelthe1** [comment]
Removed `-o` option from CLI. The recommendation is to redirect `stdout` to the desired location.
